name: PR Validation

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  call-central-pr-verification:
    name: Call Central PR Verification
    uses: chakratechgeek/centralspendshield/.github/workflows/pr-verification.yml@main
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read

  # Temporary fallback if central workflow is unavailable
  direct-pr-verification:
    name: Direct PR Verification
    runs-on: ubuntu-latest
    if: failure() # Only run if the central workflow fails
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Terraform Format Check
        run: |
          find . -name "*.tf" -exec terraform fmt -check {} \;
      
      - name: Basic validation
        run: echo "✅ Basic PR validation complete"

  pr-verification-report:
    name: PR Verification
    needs: call-central-pr-verification
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ PR validation complete"
