# repoA: .github/workflows/pr-validate.yml
name: PR Validation

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  call-central-pr-verification:
    uses: chakratechgeek/centralspendshield/.github/workflows/pr-verification.yml@main
    with: {}           # no inputs in this example
    secrets: inherit   # so your AWS_* secrets (etc.) flow through
