name: PR Validation

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  call-central-pr-verification:
    name: Call Central PR Verification
    uses: chakratechgeek/centralspendshield/.github/workflows/pr-verification-simple.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      target_repo_owner: ${{ github.repository_owner }}
      target_repo_name: ${{ github.event.repository.name }}
    secrets: inherit
