name: PR Validation (Changed Terraform + Python Output Comment)

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  find-changed-terraform:
    name: Find changed Terraform dirs
    runs-on: ubuntu-latest
    outputs:
      tf_dirs: ${{ steps.set-dirs.outputs.tf_dirs }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to diff base vs head

      - name: Ensure jq
        run: |
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y jq
          fi

      - name: Compute changed Terraform directories
        id: set-dirs
        shell: bash
        run: |
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"

          mapfile -t tf_dirs < <(
            git diff --name-only --diff-filter=ACMR "$BASE_SHA" "$HEAD_SHA" \
            | grep -E '(\.tf$|\.tfvars(\.json)?$|\.terraform\.lock\.hcl$)' \
            | xargs -n1 dirname | sort -u
          )

          echo "Changed Terraform dirs:"
          printf ' - %s\n' "${tf_dirs[@]:-<none>}"

          if [ ${#tf_dirs[@]} -eq 0 ]; then
            echo "tf_dirs=[]" >> "$GITHUB_OUTPUT"
          else
            tf_dirs_json=$(jq -c -n '$ARGS.positional' --args "${tf_dirs[@]}")
            echo "tf_dirs=$tf_dirs_json" >> "$GITHUB_OUTPUT"
          fi

  plan-and-check:
    name: Terraform plan & run check.py (per dir)
    needs: find-changed-terraform
    if: needs.find-changed-terraform.outputs.tf_dirs != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJson(needs.find-changed-terraform.outputs.tf_dirs) }}
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION:    ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps (optional)
        shell: bash
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # Single robust step that never fails the job; it writes a markdown file with results
      - name: Run plan + check.py and capture output (robust)
        id: run-check
        working-directory: ${{ matrix.dir }}
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$GITHUB_WORKSPACE/outputs"

          SANITIZED_DIR="$(echo '${{ matrix.dir }}' | sed 's/[^A-Za-z0-9_.-]/_/g')"
          DIR_HASH="$(printf '%s' '${{ matrix.dir }}' | md5sum | cut -c1-8)"
          OUT_FILE="$GITHUB_WORKSPACE/outputs/${SANITIZED_DIR}-${DIR_HASH}.md"
          echo "OUT_FILE=$OUT_FILE" >> "$GITHUB_ENV"
          echo "ART_NAME=check-output-${SANITIZED_DIR}-${DIR_HASH}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}" >> "$GITHUB_ENV"

          {
            echo "### Directory: \`${{ matrix.dir }}\`"
            echo

            INIT_OK=0
            terraform init -input=false && INIT_OK=1 || true
            if [ $INIT_OK -eq 1 ]; then
              echo "✅ terraform init"
            else
              echo "❌ terraform init failed"
            fi

            VAL_OK=0
            terraform validate && VAL_OK=1 || true
            if [ $VAL_OK -eq 1 ]; then
              echo "✅ terraform validate"
            else
              echo "❌ terraform validate failed"
            fi

            PLAN_OK=0
            terraform plan -input=false -no-color -out=plan.out && PLAN_OK=1 || true
            if [ $PLAN_OK -eq 1 ]; then
              echo "✅ terraform plan"
              # show -> plan.json
              if terraform show -json plan.out > plan.json 2>/dev/null; then
                echo
                echo "#### check.py output"
                echo '```'
                # Run your checker; if it fails, we still capture its stderr/stdout
                python "$GITHUB_WORKSPACE/check.py" plan.json || true
                echo '```'
              else
                echo "⚠️ terraform show failed; skipping check.py"
              fi
            else
              echo "❌ terraform plan failed; skipping terraform show and check.py"
            fi
          } | tee "$OUT_FILE"

      - name: Upload per-dir output (unique name)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ART_NAME }}   # guaranteed unique
          path: ${{ env.OUT_FILE }}
          if-no-files-found: error
          retention-days: 7

  aggregate-and-comment:
    name: Aggregate outputs & comment on PR
    needs: [find-changed-terraform, plan-and-check]
    if: always() && needs.find-changed-terraform.outputs.tf_dirs != '[]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: check-output-*
          merge-multiple: true
          path: collected

      - name: Build combined comment
        id: build
        shell: bash
        run: |
          echo "## Terraform Checks (Python Output)" > combined.md
          echo "" >> combined.md
          if ls collected/*.md >/dev/null 2>&1; then
            for f in $(ls -1 collected/*.md | sort); do
              echo "---" >> combined.md
              cat "$f" >> combined.md
              echo "" >> combined.md
            done
          else
            echo "_No outputs produced._" >> combined.md
          fi

      - name: Find existing comment (to update)
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: "## Terraform Checks (Python Output)"

      - name: Create or update PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ github.token }}  # same-repo PRs
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body-path: combined.md

  summary:
    name: PR Validation summary
    needs: [find-changed-terraform, plan-and-check, aggregate-and-comment]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "✅ PR validation complete"
          echo "Changed Terraform dirs: ${{ needs.find-changed-terraform.outputs.tf_dirs }}"
          echo "Plan job overall: ${{ needs.plan-and-check.result }}"
