name: PR Validation

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  call-central:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    uses: chakratechgeek/centralspendshield/.github/workflows/pr-verification.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      target_repo_owner: ${{ github.repository_owner }}
      target_repo_name: ${{ github.event.repository.name }}
    secrets:
      PR_COMMENT_TOKEN: ${{ secrets.PR_COMMENT_TOKEN }}   # or ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}


  pr-verification-report:
    name: PR Verification Report
    needs: call-central-pr-verification
    runs-on: ubuntu-latest
    if: always()
    steps:
      - run: echo "✅ PR validation complete"
